slug: solar-water-pumping-for-irrigation
brief: Design and Feasibility of a Solar-Powered Water Pumping System for
  Smallholder Irrigation in Karshi, Abuja, Nigeria
sources: []
research: true
depth: brief
status: ready
createdAt: 2026-08-12T11:31:33.188Z
updatedAt: 2026-08-12T11:36:59.155Z
