slug: mechanical-keyboards-as-typing-ergonomics
brief: Mechanical keyboards as typing ergonomics
sources: []
research: false
theme: null
maxSlides: 6
status: ready
createdAt: 2026-08-10T14:37:26.077Z
updatedAt: 2026-08-10T14:37:43.465Z
